### ISSUE TITLE
How to use host machine to access rpc service in docker container?

### ISSUE THREAD

**Issue by ioogle** [zeromicro/go-zero#1102]
I tried to use the host machine to access RPC service served in a docker container, but unfortunately, it failed. After reading the source files of `go-zero`, here written my solution:

### Scenario:

1. Both of the Etcd server and RPC service are running in docker containers
2. Wanna to use host machine to access the RPC service

### Config files:

> `POD_IP=127.0.0.1` is where the magic happens

rpc.yml:

```
Name: user.rpc
ListenOn: 0.0.0.0:55032
Etcd:
  Hosts:
    - etcd:4001
  Key: user.rpc
```

docker-compose.yml:

```
version: '3'

networks:
  default:
    driver: bridge
    name: my_proj

services:
  etcd:
    image: bitnami/etcd:latest
    container_name: my_proj_etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:4001,http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:4001,http://127.0.0.1:2379
    ports:
      - 2379:2379
    networks:
      - default
  user-rpc:
    image: /path/to/user-rpc
    container_name: my_proj_user_rpc
    environment:
      - POD_IP=127.0.0.1
    ports:
      - 55032:55032
    networks:
      - default
```
