### ISSUE TITLE
main 函数增加 kq 的启动后，Prometheus 不能启动

### ISSUE THREAD

**Issue by wuyazi** [zeromicro/go-zero#1156]
### 配置文件：
```yaml
Name: shorturl-api
Host: 0.0.0.0
Port: 8888
Transform:
  Etcd:
    Hosts:
      - localhost:2379
    Key: transform.rpc
Prometheus:
  Host: 0.0.0.0
  Port: 9091
  Path: /metrics
KqConf:
  Name: MyKq
  Brokers:
  - 10.0.4.221:9092
  Group: adhoc
  Topic: my_test1
  Offset: first
  Consumers: 1
```

### 启动文件：
```go
package main

import (
	"flag"
	"fmt"
	"github.com/tal-tech/go-queue/kq"
	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/core/threading"
	"github.com/tal-tech/go-zero/rest"
	"golang.org/x/sync/errgroup"
	"xgit.italki.com/go/shorturl/api/internal/config"
	"xgit.italki.com/go/shorturl/api/internal/handler"
	"xgit.italki.com/go/shorturl/api/internal/svc"
)

var configFile = flag.String("f", "etc/shorturl-api.yaml", "the config file")
var g errgroup.Group

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	group := threading.NewRoutineGroup()

	// kq
	group.RunSafe(func() {
		q := kq.MustNewQueue(c.KqConf, kq.WithHandle(func(k, v string) error {
			fmt.Printf("=> %s\n", v)
			return nil
		}))
		defer q.Stop()
		q.Start()
		fmt.Printf("Starting kq at %s\n", c.KqConf.Brokers)
	})

	// rest server
	group.RunSafe(func() {
		ctx := svc.NewServiceContext(c)
		server := rest.MustNewServer(c.RestConf)
		defer server.Stop()
		handler.RegisterHandlers(server, ctx)
		fmt.Printf("Starting server at %s:%d...\n", c.Host, c.Port)
		server.Start()
	})

	group.Wait()

}
```

启动后无法访问 http://127.0.0.1:9091/metrics
注释掉 qk 部分就可以访问了
```go
	// kq
	group.RunSafe(func() {
		//q := kq.MustNewQueue(c.KqConf, kq.WithHandle(func(k, v string) error {
		//	fmt.Printf("=> %s\n", v)
		//	return nil
		//}))
		//defer q.Stop()
		//q.Start()
		fmt.Printf("Starting kq at %s\n", c.KqConf.Brokers)
	})

```
