### ISSUE TITLE
解析yaml时转map出错

### ISSUE THREAD

**Issue by charmfocus** [zeromicro/go-zero#1257]
yaml
```yaml
machine:
  node1: true
  node2: true
  node3: true
```

```go
//Config

type Config struct {
    Machine map[string]bool `json:"machine,optional"`
}

c := &Config{}
conf.LoadConfig("./etc/config.yaml", c)
```

报错：
```
reflect.Value.SetMapIndex: value of type interface {} is not assignable to type bool
```

当把Config Machine类型改为 map[string]interface{}才行
```go
type Config struct {
    Machine map[string]interface{} `json:"machine,optional"`
}
```

怎么才能正常解析呢
