### ISSUE TITLE
goctl model generate from database on docker mysql latest

### ISSUE THREAD

**Issue by SpectatorNan** [zeromicro/go-zero#1406]
**Describe the bug**
my navicat and book demo can connected, but goctl model geneerate access denied

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   goctl model mysql datasource -url="root:localpwd@@tcp(127.0.0.1:3306)/book" -table="*" -c -dir .
   ```

2. The error is
 ![image](https://user-images.githubusercontent.com/13959374/147878547-f68cd1cf-35f6-414f-9a84-1bff4a4aa51b.png)

**Environments (please complete the following information):**
 - OS: Mac OS
 - go-zero version: 1.2.d
 - goctl version: 1.2.4

**More description**

my docker compose is 

```
version: '3.1'

services:

  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: localpwd
      
volumes:
    mysql_data: {}
```
