### ISSUE TITLE
Support config files for different environments

### ISSUE THREAD

**Issue by chowyu12** [zeromicro/go-zero#1555]
希望可以支持多环境配置文件，比如config-dev.yaml, config-prod.yaml的配置支持

**Comment by chenquan** [comment]
> 希望可以支持多环境配置文件，比如config-dev.yaml, config-prod.yaml的配置支持

You can use environment variables instead.
```yaml
Log:
  ServiceName: gatewayv1-rpc
  Mode: ${LOG_MODE}
```
```go
conf.MustLoad(*configFile, &c, conf.UseEnv())
```
