### ISSUE TITLE
After installing protoc using goctl, an error is thrown

### ISSUE THREAD

**Issue by Jungle-Leung** [zeromicro/go-zero#1737]
电脑：Macbook m1 pro
系统：macOS Monterty 12.3

目录结构：
```
-- docker-compose.yml
-- Dockerfile
```

docker-compose.yml
```
version: '3'

services:
  gateway:
    build: ./
    container_name: go-zero
    ports:
      - "8000:8000"
    volumes:
      - "./greet:/var/www/greet"
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: ["sh"]
```

Dockerfile文件：
```
FROM --platform=linux/arm64/v8 golang:1.16.0-alpine

MAINTAINER Jungle <875342392@qq.com>

ENV GO111MODULE on
ENV GOPROXY https://goproxy.cn/,direct
ENV GOMODCACHE $GOPATH/pkg/mod

# 安装goctl
RUN apk add --no-cache libc6-compat; \
    go install github.com/zeromicro/go-zero/tools/goctl@latest; \
    \
    # 安装protoc & protoc-gen-go
    goctl env check -i -f; \
    \
    # 设置protoc权限
    chmod -R 775 /go/bin

WORKDIR /var/www/greet

CMD /bin/bash
```

进入容器执行：
```
protoc --version
```

抛出异常：
```
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

容器版本：
```
Linux 3dfbc750f1bc 5.10.104-linuxkit #1 SMP PREEMPT Wed Mar 9 19:01:25 UTC 2022 aarch64 Linux
```
