### ISSUE TITLE
HOW TO  config model cache with redis-cluster

### ISSUE THREAD

**Issue by cgc1983** [zeromicro/go-zero#1893]
CONFIG greet.yaml file with redis cluster,3 master  and 3 slave  ,as  blow 

```yaml
CacheRedis:
  - Host: 127.0.0.1:6381
    Pass: "123456"
    Type: cluster
  - Host: 127.0.0.1:6382
    Pass: "123456"
    Type: cluster
  - Host: 127.0.0.1:6383
    Pass: "123456"
    Type: cluster
```

the go-zero terminal show the error : got 4 elements in cluster info address, expected 2 or 3
