### ISSUE TITLE
JWT token generate！ ‘key is of invalid type’

### ISSUE THREAD

**Issue by J-zuo** [zeromicro/go-zero#2001]
GUIDES->Business Developing->Demo project download

I downloaded the demo and configured the parameters, but running getJwtToken () returns an error :' Key is of invalid type'. Why is that?

user-api.yaml:
```yaml
Name: user-api
Host: 0.0.0.0
Port: 8888
Mysql:
  Datasource: root:@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
CacheRedis:
  - Host: 127.0.0.1:6379
    Pass:
    Type: node
Auth:
  AccessSecret: hello231asdf
  AccessExpire: 3600
```

Debug:Add fmt.Println(secretKey)
```golang
func (l *LoginLogic) getJwtToken(secretKey string, iat, seconds, userId int64) (string, error) {
	claims := make(jwt.MapClaims)
	claims["exp"] = iat + seconds
	claims["iat"] = iat
	claims["userId"] = userId
	token := jwt.New(jwt.SigningMethodES256)
	fmt.Println(secretKey)
	token.Claims = claims
	return token.SignedString([]byte(secretKey))
}
```

then:
```bash
 curl -i -X POST \
  http://127.0.0.1:8888/user/login \
  -H 'Content-Type: application/json' \
  -d '{
    "username":"666",
    "password":"123456"
}'
```
The result is consistent with Auth in user-api.yaml
```bash
Starting server at 0.0.0.0:8888...
hello231asdf
......

```

Where did I go wrong?
