### ISSUE TITLE
logx - The log output word break name supports customization

### ISSUE THREAD

**Issue by wang-yyi** [zeromicro/go-zero#2005]
**It is currently written dead in the code**

``` go
const (
	callerKey    = "caller"
	contentKey   = "content"
	durationKey  = "duration"
	levelKey     = "level"
	spanKey      = "span"
	timestampKey = "@timestamp"
	traceKey     = "trace"
)
```
**In other yaml configuration files, errors will be reported at the beginning of @**
For example, promtail log collection companion file
``` yaml
scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: selected
          __path__: /var/log/selected/*.log
    pipeline_stages:
      - json:
          expressions:
            level: @timestamp
```
It is wrong
