### ISSUE TITLE
The generated volumes of timezone by goctl kube not supported by alicloud ask

### ISSUE THREAD

**Issue by jsonMark** [zeromicro/go-zero#2007]
```yaml
      volumes:
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
            type: ''
          name: timezone
```
官方文档
hostPath 卷在ask 集群中不支持，所以更新的时候才会提示报错，参考：

https://help.aliyun.com/document_detail/89138.html

先重新edit 这个yaml 把hostpath  去掉吧，
如果需要挂载时区可以参考：

[https://help.aliyun.com/document_detail/172546.html](https://help.aliyun.com/document_detail/172546.html?spm=5176.smartservice_service_chat.0.0.41123f1bx1Uu0r)
