### ISSUE TITLE
load config with user defined struct fails with `value type is not struct`

### ISSUE THREAD

**Issue by czyt** [zeromicro/go-zero#2056]
I have a config file
```yaml
name: starMgmt-api
host: 0.0.0.0
port: 8888
mongo:
  addr: "mongodb://jack@star/?ssl=false"
  dbname: "testdb"

```
and the config struct
```go
type Config struct {
	rest.RestConf
	Jwt   Jwt
	Mongo Mongo
}

type Mongo struct {
	Addr   string
	DBName string
}

type Jwt struct {
	AccessSecret string
	AccessExpire int64
}
```
I can marshal the config into the struct via the code
```go
import(
 "gopkg.in/yaml.v3"
)
var t Config
err := yaml.Unmarshal([]byte(c), &t)
log.Println(t.Mongo)
if err != nil {
log.Fatalf("error: %v", err)
}
```
however,I fail with the go-zero method
```go
var cf *config.Config
	err = conf.LoadFromYamlBytes([]byte(c), &cf)
	if err != nil {
		log.Println(err)
	}
```
which display error
```
value type is not struct
```
