### ISSUE TITLE
when log mode config file or volume ,the program print to console

### ISSUE THREAD

**Issue by sdhczw** [zeromicro/go-zero#2257]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   package main
   import (
	"bookstore/api/internal/config"
	"bookstore/api/internal/handler"
	"bookstore/api/internal/svc"
	"flag"
	"fmt"
	"github.com/zeromicro/go-zero/core/logx"

	"github.com/zeromicro/go-zero/core/conf"
	"github.com/zeromicro/go-zero/rest"
     )

     var configFile = flag.String("f", "etc/bookstore-api.yaml", "the config file")

     func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	logx.Info("before logx =======")
	ctx := svc.NewServiceContext(c)
	server := rest.MustNewServer(c.RestConf)
	defer server.Stop()

	handler.RegisterHandlers(server, ctx)
	logx.Info("after logx =======")
	fmt.Printf("Starting server at %s:%d...\n", c.Host, c.Port)
	server.Start()
     }

   ```

```yaml

Name: bookstore-api
Host: 0.0.0.0
Port: 8888
MaxConns: 10000
Timeout: 10000 #ms
MaxBytes: 104857600
Log:
  Mode: file 
  Path: ../testdata/logs
  Level: info
  Compress: false
  KeepDays: 7

   ```

2. The error is

   ```
    when config logs mode is file or volume ,"after logx =======" not print  into file 
   ```

**Expected behavior**
 logs print into file not to console

**Screenshots**

**Environments (please complete the following information):**

 gozero 1.3.5

**More description**
