### ISSUE TITLE
Unable to set default values in config

### ISSUE THREAD

**Issue by a0v0** [zeromicro/go-zero#2266]
I am unable to set default value to config 

`etc/config.yaml`
```yaml
Media:
 
  MediaImageMaxSize: ${MEDIA_IMAGE_MAX_SIZE}

  MediaVideoMaxSize: ${MEDIA_VIDEO_MAX_SIZE}

  MediaDescriptionMaxLength: ${MEDIA_DESCRIPTION_MAX_LENGTH}

  MediaVideoTitleMaxLength: ${MEDIA_TITLE_MAX_LENGTH}
```

`config.go`
```go
Media struct {
        MediaImageMaxSize         int64 `json:",default=5242880"`
        MediaVideoMaxSize         int64 `json:",default=41943040"`
        MediaDescriptionMaxLength int64 `json:",default=150"`
        MediaVideoTitleMaxLength  int64 `json:",default=25"`
    }
```

But I am getting this error
```
2022/08/15 23:17:28 error: config file etc/config.yaml, error: type mismatch for field Media.MediaImageMaxSize
exit status 1
```

also vscode shows warning as shown in the image. 
I think values from default tag are not being read. Any idea?

![image](https://user-images.githubusercontent.com/62926341/184928528-8e9bfd75-c8e2-47b3-a544-657cc14d750f.png)
