### ISSUE TITLE
More logs about set key to etcd discovery when failed

### ISSUE THREAD

**Issue by akalittle** [zeromicro/go-zero#2468]
As I have set in config
```yaml
Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: txstatus.rpc
```

It works fine on my development machine.
I can see the key in etcd.
<img width="354" alt="image" src="https://user-images.githubusercontent.com/38489160/192955872-9a7f4771-1a26-42da-9b5b-930c58666a8c.png">

But when I deployed the image to GCP k8s environment.
The key is not setted, and there is no log why this key is not setted successfully.
