### ISSUE TITLE
The func httpx.Parse Data struct have a UnmarshalJsonReader's Bug, can't parse []map[string]string structure type.

### ISSUE THREAD

**Issue by bmomhan** [zeromicro/go-zero#2684]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is
test.http
```
###
#用户申请退款消息 SPI
POST http://localhost:8888/test
Content-Type: application/json

{
  "order_id": "1234567",
  "refund_reason": {
    "reason_code": [
      123,
      234
    ],
    "desc": "不想要了",
    "show_reason": [
      {
        "123": "货品不足",
        "234": "已经打烊"
      }
    ]
  },
  "product_detail": {
    "product_id": "123",
    "sku_id": "123",
    "name": "小蛋糕",
    "actual_amount": 100
  }
}

###
```
test_entity.go
   ```go
   type OrderApplyRefundReq struct {
	OrderId       string            `json:"order_id"`
	RefundReason  RefundReasonData  `json:"refund_reason,optional"`
	ProductDetail ProductDetailData `json:"product_detail,optional"`
}

type RefundReasonData struct {
	ReasonCode []int               `json:"reason_code"`
	Desc       string              `json:"desc"`
	ShowReason []map[string]string `json:"show_reason"`
}

type ProductDetailData struct {
	ProductId    string `json:"product_id"`
	SkuId        string `json:"sku_id"`
	Name         string `json:"name"`
	ActualAmount int    `json:"actual_amount"`
}

   ```

3. The error is

   ```
metrics:
    unreadable: protocol error E08 during memory read for packet $m83486f7610663b49,5...
container:
    unreadable: could not read string len protocol error E08 during memory read for packet $m4868246c894870ec,4...
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. macOs]
 - go-zero version [e.g. 1.3.5]
 - goctl version [e.g. 1.3.8, optional]

**More description**
