### ISSUE TITLE
if service port and target port are different, then rpc call will failed (using k8s endpoint sd)

### ISSUE THREAD

**Issue by zhangsure** [zeromicro/go-zero#2852]
### user rpc service yaml
```
apiVersion: v1
kind: Service
metadata:
  name: go-zero-rpc-user-svc
  namespace: test-ns
spec:
  ports:
    - name: go-zero-rpc-user-port
      protocol: TCP
      port: 3456
      targetPort: 8080
  selector:
    app: go-zero-rpc-user
```
### order api service yaml
```
apiVersion: v1
kind: Service
metadata:
  name: go-zero-api-order-svc
  namespace: test-ns
spec:
  ports:
    - name: go-zero-api-order-port
      protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    app: go-zero-api-order
```
### order api conf
```
Name: order
Host: 0.0.0.0
Port: 8888
Mode: dev
UserRpc:
  Target: k8s://test-ns/go-zero-rpc-user-svc:3456
  NonBlock: true
```
### services in k8s
```
kubectl get services -n test-ns
```      
NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP                PORT(S)          AGE
go-zero-api-order-svc   NodePort       10.247.101.172   <none>                     8888:30341/TCP   31m
go-zero-rpc-user-svc    ClusterIP      10.247.162.18    <none>                     3456/TCP         31m

### endpoints in k8s
```
kubectl get ep -n test-ns -o wide
```                     
NAME                    ENDPOINTS                                       AGE
go-zero-api-order-svc   10.0.0.22:8888,10.0.1.145:8888,10.0.1.24:8888   31m
go-zero-rpc-user-svc    10.0.0.21:8080,10.0.1.144:8080,10.0.1.23:8080   32m

### http get and rpc error
```
# 11.54.85.109 is a k8s node ip
curl -X GET http://11.54.85.109:30341/api/order/get/1 
```
rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp **10.0.0.21:3456**: connect: connection refused"
rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp **10.0.1.23:3456**: connect: connection refused"
rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp **10.0.1.144:3456**: connect: connection refused"

**is it wrong here? dial tcp x.x.x.x:3456? 
it's should be x.x.x.x:8080**

I try to change `user rpc service Port` and `order api conf Target`  from 3456 to 8080 (same as TargetPort)  in yamls
then everything will be OK

**Comment by kevwan** [comment]
```yaml
Name: order
Host: 0.0.0.0
Port: 8888
Mode: dev
UserRpc:
  Target: k8s://go-zero-rpc-user-svc.test-ns:3456
  NonBlock: true
```
