### ISSUE TITLE
etcd error:retrying of unary invoker failed

### ISSUE THREAD

**Issue by Arrowarcher** [zeromicro/go-zero#3055]
配置etcd后，启动后一段时间开始不断报错，内容如下：
{"level":"warn","ts":"2023-03-22T12:42:04.341+0800","logger":"etcd-client","caller":"v3@v3.5.7/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target
":"etcd-endpoints://0xc0000f9500/10.0.160.95:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connecti
on error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:2379: connectex: No connection could be made because the target machine actively refused it.\""}  
{"level":"info","ts":"2023-03-22T12:42:04.342+0800","logger":"etcd-client","caller":"v3@v3.5.7/client.go:210","msg":"Auto sync endpoints failed.","error":"context deadl
ine exceeded"}

yaml:
```yaml
Name: base-rpc
ListenOn: 0.0.0.0:2004
Mode: dev
# 测试生产使用k8s部署时不需要使用etcd
Etcd:
  Hosts:
  - 10.0.160.95:2379
  Key: base123.rpc
```

ETCD里可以看到注册key：
`I have no name!@84340845d47c:/opt/bitnami/etcd$ etcdctl get --prefix "base123.rpc"
base123.rpc/7587869282812747745
192.168.11.14:2004`
