### ISSUE TITLE
rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by liamhao** [zeromicro/go-zero#3140]
**Describe the bug**
Communication between `grpc-gateway` and `rpc` service failed：
```
rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**To Reproduce**

go version: 1.18
go-zero version: v1.5.1

etc/sum.yaml
```yaml
Name: sum.rpc
ListenOn: 127.0.0.1:8080
Gateway:
  Name: gateway
  Port: 8081
  Upstreams:
    - Name: rpc-server
      Grpc:
        Endpoints:
          - localhost:8080
      ProtoSets:
        - sum.pb
```

internal/config/config.go
```go
package config

import (
	"github.com/zeromicro/go-zero/gateway"
	"github.com/zeromicro/go-zero/zrpc"
)

type Config struct {
	zrpc.RpcServerConf
	Gateway gateway.GatewayConf
}
```

sum.proto
```proto
syntax = "proto3";

package sum;
option go_package="./pb";

import "google/api/annotations.proto";

message SumRequest {
    int64 a = 1;
    int64 b = 2;
}

message SumResponse {
    int64 result = 1;
}

service Sum {
    rpc Add(SumRequest) returns (SumResponse) {
		option (google.api.http) = {
			post: "/v1/sum"
			body: "*"
		};
	}
}
```

other file source code here：https://github.com/kevwan/grpc-restful

run command:
`curl -d '{"a":2,"b":3}' -H 'Content-Type: application/json' localhost:8081/v1/sum`

2. The error is
```
rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**Expected behavior**
Hope grpc-gateway and rpc service can communicate normally.

**Screenshots**
server:
![image](https://user-images.githubusercontent.com/31812811/233006185-8decb899-ea35-4615-9f75-a576c3de40a9.png)

cmd result:
![image](https://user-images.githubusercontent.com/31812811/233006289-8ac57675-18b9-4728-a262-ae3df61f0e3b.png)

**Environments (please complete the following information):**
 - OS: Linux
 - go-zero version 1.5.1
 - goctl version 1.5.1 linux/amd64

**More description**
