### ISSUE TITLE
feat: need OtlpHttpPath config support for ZincObserve Telemetry

### ISSUE THREAD

**Issue by toby1991** [zeromicro/go-zero#3270]
**Is your feature request related to a problem? Please describe.**
Export tracing data to ZincObserve need add a http path config support for OTLPHTTP method.

**Describe the solution you'd like**
Add an OtlpHttpPath in the gozero's Telemetry config like below:

```yaml

Telemetry:
  Name: api-api
  Endpoint: 172.26.246.157:5080
  Sampler: 1.0
  Batcher: otlphttp
  OtlpHeaders:
    Authorization: "Basic balabala"
  OtlpHttpPath: /api/default/traces

```

**Describe alternatives you've considered**
I'll create a pr

**Additional context**
> https://zinc.dev/docs/guide/telemetry/

<img width="880" alt="image" src="https://github.com/zeromicro/go-zero/assets/5897356/84bfec94-ac4f-4723-808d-569ed7dee05d">
