### ISSUE TITLE
Only for first run of rpc service with newly started etcd cluster, msg:retrying of unary invoker failed rpc error: code = Canceled desc = context canceled

### ISSUE THREAD

**Issue by info193** [zeromicro/go-zero#3425]
etcd版本：bitnami/etcd:3.5.9
gozero版本:1.5.3
rpc 配置文件
```
Name: demo.rpc
ListenOn: 0.0.0.0:10058
Etcd:
  Hosts:
    - 192.168.7.75:2379
    - 192.168.7.75:3379
    - 192.168.7.75:4379
  Key: demo.rpc
```
etcd集群环境配置、rpc配置文件多个hosts 第一次启动rpc报错，使用正常，不受影响，后面再次启动rpc运行也不报错。
```
{"level":"warn","ts":"2023-07-14T15:29:16.265366+0800","logger":"etcd-client","caller":"v3@v3.5.9/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0006c68c0/192.168.7.75:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
```
注：如果只配置一个rpc配置文件 hosts正常启动且使用正常不报错。
### etcd health 正常
![f89ee53f79e5ecf1d1ae5a0a8f90709](https://github.com/zeromicro/go-zero/assets/50605978/7349b27d-c1dc-48ff-9f00-94ddc66f8034)

操作流程：安装etcd，启动etcd集群，在集群启动成功后，开始第一次启动rpc就会报错。
复现流程：关闭etcd集群，然后在启动etcd集群，再次开始第一次启动rpc也会报错。

docker-compose.yaml文件
```
  etcd1:
    image: bitnami/etcd:3.5.9  
    container_name: etcd1      
    restart: always             
    networks:
      - etcd-net              
    ports:
      - "2379:2379"
      - "2380:2380"
    environment: # 环境变量 --env
      - ALLOW_NONE_AUTHENTICATION=yes                      
      - ETCD_NAME=etcd1                                    
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.7.75:2380  
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380          
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379        
      - ETCD_ADVERTISE_CLIENT_URLS=http://192.168.7.75:2379        
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster           
      - ETCD_INITIAL_CLUSTER=etcd1=http://192.168.7.75:2380,etcd2=http://192.168.7.75:3380,etcd3=http://192.168.7.75:4380 
      - ETCD_INITIAL_CLUSTER_STATE=new                     
   etcd2:
    ...
   etcd3:
    ...
```
