### ISSUE TITLE
etcd in the gateway configuration cannot inherit the defined

### ISSUE THREAD

**Issue by eyjian** [zeromicro/go-zero#3925]
Do not configure Hosts in Upstreams:

```yaml
Etcd:
  Hosts:
    - 127.0.0.1:2379

Login: # Login service client conf
  Prefix: /v1
  Etcd:
    Key: mooonlogin.rpc

Auth: # Authentication service client conf
  Prefix: /v2
  Etcd:
    Key: mooonauth.rpc

Upstreams: # upstreams
  - Grpc:
      Etcd:
        #Hosts:
        #  - 127.0.0.1:2379
        Key: mooonlogin.rpc
```

Error when running:

```
config file etc/gateway.yaml, type mismatch for field "Upstreams[0].Grpc.etcd.Hosts"
```
