### ISSUE TITLE
Use servicegrouyp create http server set log mode file ,but Not in effect

### ISSUE THREAD

**Issue by vector4wang** [zeromicro/go-zero#4171]
i use service group Implement asynq server and http service:
core.go
```golang
func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)

	serviceGroup := service.NewServiceGroup()
	defer serviceGroup.Stop()

	for _, mq := range listen.Services(c) {
		serviceGroup.Add(mq)
	}

	serviceGroup.Start()
	
}
```

listen.go
```golang
func Services(c config.Config) []service.Service {
	svcContext := svc.NewServiceContext(c)
	ctx := context.Background()
	var services []service.Service

	server := rest.MustNewServer(c.RestConf)
	defer server.Stop()

	handler.RegisterHandlers(server, svcContext)

	services = append(services, server)
	//asynq ： 延迟队列、定时任务
	services = append(services, AsynqService(c, ctx, svcContext)...)
	return services
}
```

and log config
```yaml
Name: core-api
Host: 0.0.0.0
Port: 8080
Timeout: 60000

Log:
  Mode: "file"
  Encoding: "plain"
  ServiceName: "asynq-service"
  TimeFormat: "2006-01-02 15:04:05"
  Path: "logs"
  Level: "info"
  
Redis:
  Host: "localhost:6379"
  Type: node
  Pass: "123456"

```

When I use log to output logs, the logs are still output on the console and are not written to the file！
However, other log configurations are valid, such as date format and encoding：

```text
2024-06-01 00:00:12      info   [HTTP]  200  -  GET  /from/you - [::1]:56882 - PostmanRuntime/7.39.0    duration=8.6ms  caller=handler/loghandler.go:147        trace=466f57b623c9e05831697d37af2561f0  span=28f9536997e81e73
push : {To:you Subject:me Body:e47752f5-5ae3-484a-a11c-c06c10567a14} 

```

After comparison, it can be determined that the problem is the startup method of servicegroup, but I do not know what causes it, help you big guys
