### ISSUE TITLE
In concurrent scenarios, API calls to RPC may result in context cancel

### ISSUE THREAD

**Issue by z406497819** [zeromicro/go-zero#4303]
**Describe the bug**
Here we used the example of API calling RPC in the greet demo,
The implementation logic is very simple, it just outputs hello world
At first, I thought it was a version issue. Go Zero upgraded from 1.6.0 to 1.6.5 and then to 1.7.0, but this problem still occurs
The higher the concurrency, the greater the probability of occurrence
At concurrency of 100, it is almost inevitable
The only change made was sleeping for 5 seconds in the RPC layer

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

rpc:
   ```yaml
Name: car.rpc
ListenOn: 0.0.0.0:8081
Timeout: 60000
   ```

   ```go
   // logic
func (l *PingLogic) Ping(in *car.Req) (*car.Resp, error) {

	time.Sleep(time.Second*5)

	return &car.Resp{
		Pong: "hello",
	}, nil
}
   ```

api:
```yaml
Name: car
Host: 0.0.0.0
Port: 8889
Timeout: 60000

CarRpc:
  Timeout: 60000
  Endpoints:
    - 192.168.1.3:8081
```

```go
func (l *TestLogic) Test() (resp *types.Resp, err error) {

	res, err := l.svcCtx.CarRpc.Ping(l.ctx, &car.Req{})
	if err != nil {
		return
	}

	return &types.Resp{
		Name: res.Pong,
	}, nil
}

```

2. The error is

   ```
  http response status:408
   rpc error: code = Canceled desc = context canceled
   ```

**Screenshots**
![image](https://github.com/user-attachments/assets/30d73fc9-6e07-4555-bbc9-f4208f35d5d1)

**Environments (please complete the following information):**
 - OS: linux
 - go version 1.22.1
 - go-zero version 1.7.0
 - goctl version 1.7.0

Hope to solve this problem, thank you everyone
