### ISSUE TITLE
When generate model using goctl, the numeric type is treated as a bigint

### ISSUE THREAD

**Issue by smokecat** [zeromicro/go-zero#4435]
**Describe the bug**
A field of type `numeric` in the PostgreSQL database is generated as `int64`. And the `numeric` database type is treated as a `bigint` type in `goctl.yaml`

**To Reproduce**

1. The sql is

   ```sql
   create table demo (
     id bigint generated always as identity primary key,
     max_position decimal(20, 4) not null
   );
   ```

2. The genereated model struct is

   ```go
   TradingRobotSetting struct {
     Id               int64          `db:"id"`
     MaxPosition      int64          `db:"max_position"`
   }
   ```

3. The `goctl.yaml` is

   ```yaml
   model:
     types_map:
        bigint:
          null_type: sql.NullInt64
          type: int64
          unsigned_type: uint64
        decimal:
          null_type: decimal.NullDecimal
          pkg: github.com/shopspring/decimal
          type: decimal.Decimal
   ```

**Expected behavior**
The type of MaxPosition is `decimal.Decimal`

**Environments (please complete the following information):**
 - go-zero version 1.7.2
 - goctl version 1.7.2

**Comment by kesonan** [comment]
I have reproduced it here and it can be generated normally. Please make sure your goctl version is greater than or equal to 1.6.5

**Comment by smokecat** [comment]
Thank you, I'll try this feature later

**Comment by smokecat** [comment]
I've been able to reproduce this issue steadily in the latest 1.7.5 release.

**Comment by pandajc** [comment]
@smokecat hello, I have tryied and seems it still cannot recognize  numeric datatype in postgresql, it was generated to int64 rather than custom type(mine is big.Int)
**PostgreSQL  DDL**

```
CREATE TABLE balance_tab (
	id bigserial NOT NULL,
	balance numeric(78) DEFAULT 0 NOT NULL
);
```

**goctl.yaml**

```
model:
  types_map:
    bigint:
      null_type: sql.NullInt64
      type: int64
      unsigned_type: uint64
    numeric:
      null_type: big.Int
      type: big.Int
      pkg: math/big
```

**goctl version 1.7.5**
