### ISSUE TITLE
otlphttp batcher bug

### ISSUE THREAD

**Issue by MYHZ79** [zeromicro/go-zero#4455]
hi there

with this config:
```yaml
Telemetry:
  Name: gateway-api
  Endpoint: http://localhost:8080/v1/traces
  Sampler: 1.0
  Batcher: otlphttp
```
i get this error:
`{"@timestamp":"2024-11-09T17:35:00.118+03:30","caller":"trace/agent.go:148","content":"[otel] error: traces export: parse \"http://http:%2F%2Flocalhost:8080%2Fv1%2Ftraces/v1/traces\": invalid port \":8080%2Fv1%2Ftraces\" after host","level":"error"}
`
go-zero v1.7.3
i am using [coroot](https://coroot.com/) as my APM
