### ISSUE TITLE
http gateway的配置写上Prefix就无法获取响应

### ISSUE THREAD

**Issue by wisonlau** [zeromicro/go-zero#4813]
gateway.yaml

问题1: 

写上Prefix就无法获取响应
```yaml
  - Name: testservice
    Http:
      Target: 127.0.0.1:10010
      Prefix: /test
      Timeout: 3000
    Mappings:
      - Method: GET
        Path: /hello
      - Method: POST
        Path: /hi
```

问题2:
一个地址有前缀,一个地址没有前缀; 如果后缀的名字相同则无法启动

```json
{"@timestamp":"2025-04-28T18:45:13.681+08:00","caller":"rest/server.go:324","content":"duplicated item for /hello","level":"error"}
```

```yaml
  - Name: userservice
    Http:
      Target: 127.0.0.1:10010
#      Prefix: /
      Timeout: 3000
    Mappings:
      - Method: GET
        Path: /hello
      - Method: POST
        Path: /hi

  - Name: testservice
    Http:
      Target: 127.0.0.1:10010
      Prefix: /test
      Timeout: 3000
    Mappings:
      - Method: GET
        Path: /hello
      - Method: POST
        Path: /hi
```

**Comment by wisonlau** [comment]
v1.8.2

[gateway_gozero.zip](https://github.com/user-attachments/files/20012638/gateway_gozero.zip)

**Comment by kevwan** [comment]
Hello @wisonlau,

Thank you for reporting this issue. I'd like to clarify how the current prefix handling works in our gateway component and propose a solution for the issues you're experiencing.

## Current behavior

The current implementation of `Prefix` in the gateway is different from what you might expect. Here's how it works:

1. When you configure a `Prefix` like `/test` for an upstream with a path like `/hello`, the gateway forwards requests to `/test/hello`, not to `/hello` on a backend that expects `/test/hello`.

2. This means that if your backend API expects requests at paths like `/test/hello`, you should **not** set a prefix but instead include the full path in your mappings:

```yaml
Http:
  Target: 127.0.0.1:10010
  # No prefix
  Timeout: 3000
  Mappings:
    - Method: GET
      Path: /test/hello
```

3. For your second issue with duplicate routes, this is expected behavior because our router doesn't distinguish between routes based on their upstream targets. When you have two mappings with the same HTTP method and path (like `/hello`), the router sees them as duplicates even if they're meant for different backends.

## Proposed enhancement

We understand that this behavior might not be what users expect, especially those familiar with Nginx's `proxy_pass` directive which has two different behaviors:

1. **With URI in proxy_pass**: Replaces the matched location with the specified URI
2. **Without URI in proxy_pass**: Strips the matched location prefix

We're considering enhancing our gateway to support both behaviors through new configuration options, similar to how Nginx works. This would give you more flexibility in how paths are handled when forwarded to backend services.

## Workaround for now

For your current issue, you have a few workarounds:

1. For the prefix issue: Define full paths in your mappings as shown above
2. For the duplicate routes issue: Use unique path patterns for each service, such as:
   - `/service1/hello` for one service
   - `/service2/hello` for another service

Thank you for helping us improve go-zero. We'll consider your feedback as we work on enhancing the gateway's path handling capabilities.
