### ISSUE TITLE
When the disabled configuration of rest telemetry is set to true, the log loses the trace

### ISSUE THREAD

**Issue by jaronnie** [zeromicro/go-zero#4881]
```yaml
rest:
    devServer:
        enabled: false
    telemetry:
        name: "xxx"
        endpoint: "http://127.0.0.1:14268/api/traces"
        sampler: 1.0
        batcher: "jaeger"
        disabled: true
```

I hope to decide whether to send the trace to something like jaeger by disabled, but when disabled is true, the log print loses the trace
